all:
  children:
    nginx:
      hosts:
        nginx01:
          ansible_host: 52.195.245.5
    webapp:
      hosts:
        webapp01:
          ansible_host: 52.195.245.5
        webapp02:
          ansible_host: 176.32.84.151
    db:
      hosts:
        db01:
          ansible_host: 54.64.61.102
